[package]
name = "hyper-microservice-with-handlers"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
hyper = { version = "1.7.0", features = ["full"] }
vercel_runtime = "0.1"
tokio = { version = "1.0", features = ["full"] }
